export const OPEN_EDIT_FORM = 'ui/OPEN_EDIT_FORM';
export const CLOSE_EDIT_FORM = 'ui/CLOSE_EDIT_FORM';
export const OPEN_CONFIRMATION_DIALOG = 'ui/OPEN_CONFIRMATION_DIALOG';
export const CLOSE_CONFIRMATION_DIALOG = 'ui/CLOSE_CONFIRMATION_DIALOG';
export const OPEN_INFO_DIALOG = 'ui/OPEN_INFO_DIALOG';
export const CLOSE_INFO_DIALOG = 'ui/CLOSE_INFO_DIALOG';
